services:
  mongo:
    image: mongo:7
    command: ["--quiet", "--logpath", "/dev/null"] #remover logs do driver do mongo para apenas ver o log do Jest
    logging:
      driver: "none"
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: agenda
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 120s
      timeout: 5s
      retries: 5
      start_period: 20s
  api:
    build:
      context: ./agenda_telefonica
      dockerfile: Dockerfile
    env_file:
      - ./agenda_telefonica/.env
    volumes:
      - ./agenda_telefonica:/app
      - /app/node_modules
    command: ["npm", "run", "test", "--", "--watchAll=false"]
    restart: "no"
volumes:
  mongo_data:
  mongo_config: